#!/bin/bash
#the file should be in ~/Script
#we check the first line of script 
#to measure it's bash script or not. 
#Then we use chmod u+x make it executable.
#the Script will go through 
#two layers the dirctory in ~/Script/

SCR_HEAD="#!/bin/bash"
ORI_PWD=`pwd`
#go to the directory of current file
SCR_DIR=`dirname $0`
cd ${SCR_DIR}

#list all the directory
DIR_LIST=`ls -C`

#scan all the directories
for SCR_DIR in ${DIR_LIST}
do
	#check if it's directory
	if [ -d ${SCR_DIR} ]
	then
		#enter the directory
		cd ${SCR_DIR}
		echo "enter ${SCR_DIR}"

		#list all the content
		FILE_LIST=`ls -C --hide=*~ ./`	

		#scan all the files in directory
		for SCR_FILE in ${FILE_LIST}
		do
			#check if the file is regular file
			if [ -f ${SCR_FILE} ]
			then		
				#check the first line of file
				FIRST_LINE=`head -n 1 ${SCR_FILE}`
				if [ ! ${SCR_HEAD} = ${FIRST_LINE} ]
				then
					echo "${SCR_FILE} is not script"
				else
					#check if the file is executable
					if [ ! -x ${SCR_FILE} ]
					then
						chmod u+x ${SCR_FILE}
						echo "${SCR_FILE} change to executable"
					fi
				fi
			fi
		done
	
		#exit the directory
		cd -
	fi
done

cd ${ORI_PWD}
